version: 2.1

orbs:
  hugo: circleci/hugo@0.2
  aws-s3: circleci/aws-s3@1.0.16

jobs:
  deploy-site:
    docker:
    - image: 'cimg/python:3.6'
      environment:
        AWS_REGION: us-east-1
    steps:
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          arguments: '--delete'
          from: ~/public/
          to: 's3://status.sba.gov/'
workflows:
  version: 2

  build-deploy:
    jobs:
    - hugo/build:
        html-proofer: false
        version: '0.73'
        filters:
          branches:
            only: [master]
          tags:
            only: [deploy]
    - deploy-site:
        context: sba-gov-upper
        requires:
          - hugo/build
        filters:
          branches:
            only: [master]
          tags:
            only: [deploy]
