name: Configure AWS CLI
description: Authenticate to AWS

inputs:
  oidc_role_arn:
    description: arn of the oidc role
    required: true
  region:
    description: The AWS Region. Default is us-east-1
    required: false
    default: us-east-1

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export AWS_ROLE_ARN=${{ inputs.oidc_role_arn }}
        export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
        export AWS_DEFAULT_REGION=${{ inputs.region }}
        echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
        echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
        echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

